sudo: required
env:
  global:
  - ANSIBLE_VERSION=2.5
  - secure: ZDHhPSt2NLRs6qBFDWqgbuqdW0q0GPhq4bXEqAh/cjdSECVyjYoq1ii+VrMf1sq5YFQW85zICahKNTEK/wCTAykM/r9ktyu9qa6MrUQt6GAaaaD2tMr3fIZ5y5531pfjIUK3qCrzGInHMTLZa+OtziwFQFyRzmG2sS/hIN2KONPZ+2f8LxARAnw+ZVuEOvFANKz9lYFWOnfiYwshG6YxQgoBqN3c1GIad3UbIK2Z2gha0Y06JX5HrsCWkJJrP8+E1MBTwY2QqsCYlwc1DJGT6mshXCOmebJYxMXacxVUOIJdkP3gLPlq7hiAjuoE8dmZ3kOMpxnJQi0lju1KGMNM/BugrtcULwTMJDw01MUgpjjnnM0RlsGJrNaVMFZ+1I+SiTX6noGxtvgZJMMAwwVLrCJuYj/dGYuHXnhclKB2rnlRewbz57fDj0iDM+y0BCrwS63nF9lh4keUr/1ZelV24/4eQ5kNMZiWpMRJtGBhJZFoDI0l0vHzpmRCvztAu8LG+yc+UrHof+xGcd7caoo3pPD9ehi574dBp8JOnyibGEJBMDBfy4UoM0Om9FlFUgf8pUPQNa252BW8Teq7vnuf0V65zmdQr+q/QaId6AJqj4lAE89/L7wVGPwLczce+E96Hv6giVWOoeCSlEn43iH+XFk0lOAIvRG4oYF8Ju7KKUQ=
  - secure: UYfEumvStmJ29ky/5Xu8sZe+YOJ8lSUuoPFUnia4BvT0VYfyrCNHSKo+upu7QVUDwN74EwX5CGePGB8fKjCJMf7nyBMd3iWCyF6OagEMnTtJu9vNjEKe0nBJyOFwR5Qyiek7Ldl9sPFqEsiin7aGNeIKT3uPjhPoMTAdCCTEFlJ2O7E51l3TEn9m/kUClfqCQY/LUjCGUduixQnmwDlsaK27Tjnnc4ktl+2kPZCnYXdkF9qIQ5tb1omJzOIvyDA1tN3oHsVfprqwjcDB+RK/fCBxUPyzSnNJjzWk17IzWzb/rgOBrFwrvIlxBBI6bc3d4tY0rqPzgZmx0KvU70pLdVlfLidXqxClD6wIhKQsOaYF7UfF5R9SYqiekj4X7kY/wW12s0pePpANHQ/sRAfzGT+pFcBAiB5IYwh7qcvpZbcG+3us1gP59W82R4dd0R8JawLouVguXOdJuUqbC1Y9Kfr3ONiMfYPEhXA+eZH/obluTzvmgqPxINJDVJAAw/aMC78YEyQoT6WACk/AitRVKIOOzvv/W9rZ++E993J6/qC+gN2wvnwViMQVU9Yc7EENiQuqjHtunGA4VxC2+fWHg5hXoSob5/HrYNv7L0n8bXcNMJYEeZm63F8tezGSTvRhR0l35nQpKF7IakBGIo64VNg08QKNJTUrNfPAeXU/wAo=
  matrix:
  - DISTRIBUTION: centos
    VERSION: 7
  - DISTRIBUTION: ubuntu
    VERSION: 16.04
services:
- docker
before_install:
- sudo apt-get update
- sudo apt-get install --only-upgrade git
- git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
- git fetch origin docker-tests
- git worktree add docker-tests origin/docker-tests
- sudo pip install --upgrade pip
- sudo pip install ansible-lint yamllint
script:
- ansible-lint . -x ANSIBLE0016
- yamllint .
- ./docker-tests/docker-tests.sh
- SUT_ID=$(docker ps -qa) ./docker-tests/functional-tests.sh
