---

- name: "oiofs: Unmount filesystem (by stopping gridinit service)"
  command: "gridinit_cmd stop {{ mountpoint.namespace | default(oiofs_mountpoint_default_namespace) }}-oiofs-{{ mountpoint_id }}"
  ignore_errors: true
  tags: configure

- name: 'oiofs: Remove oiofs configuration files'
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - "{{ openio_oiofs_conf_directory }}/{{ mountpoint_id }}.json"
    - "{{ oiofs_logrotate_template_conf_path }}"
    - "{{ oiofs_rsyslog_conf_path }}"
    - "{{ openio_gridinit_conf_confd + '/' + (mountpoint.namespace |
      default(oiofs_mountpoint_default_namespace)) + '/oiofs-' + mountpoint_id + '.conf'
      if openio_gridinit_per_ns else openio_gridinit_conf_confd + '/' + (mountpoint.namespace |
      default(oiofs_mountpoint_default_namespace)) + '-oiofs-' + mountpoint_id + '.conf' }}"
  register: _delete_files
  tags: configure

- name: "oiofs: Reload gridinit"
  systemd:
    name: gridinit
    state: reloaded
  when: _delete_files is changed
  tags: configure

...
